#ifndef __MESSAGEBOX_H
#define __MESSAGEBOX_H

#include <linux/ioctl.h> /* needed for the _IOW etc stuff used later */

#define MESSAGEBOX_IOC_MAGIC  'k'
#define MESSAGEBOX_IOCRESET     _IO(MESSAGEBOX_IOC_MAGIC,   0)

#define MESSAGEBOX_IOCSMODE     _IOW(MESSAGEBOX_IOC_MAGIC,  1,  int)
#define MESSAGEBOX_IOCSGLIM     _IOW(MESSAGEBOX_IOC_MAGIC,  2,  int)
#define MESSAGEBOX_IOCSULIM     _IOW(MESSAGEBOX_IOC_MAGIC,  3,  int)

#define MESSAGEBOX_IOCTMODE     _IO(MESSAGEBOX_IOC_MAGIC,   4)
#define MESSAGEBOX_IOCTGLIM     _IO(MESSAGEBOX_IOC_MAGIC,   5)
#define MESSAGEBOX_IOCTULIM     _IO(MESSAGEBOX_IOC_MAGIC,   6)

#define MESSAGEBOX_IOCGMODE     _IOR(MESSAGEBOX_IOC_MAGIC,  7,  int)
#define MESSAGEBOX_IOCGGLIM     _IOR(MESSAGEBOX_IOC_MAGIC,  8,  int)
#define MESSAGEBOX_IOCGULIM     _IOR(MESSAGEBOX_IOC_MAGIC,  9,  int)

#define MESSAGEBOX_IOCQMODE     _IO(MESSAGEBOX_IOC_MAGIC,   10)
#define MESSAGEBOX_IOCQGLIM     _IO(MESSAGEBOX_IOC_MAGIC,   11)
#define MESSAGEBOX_IOCQULIM     _IO(MESSAGEBOX_IOC_MAGIC,   12)

#define MESSAGEBOX_IOCXMODE     _IOWR(MESSAGEBOX_IOC_MAGIC, 13, int)
#define MESSAGEBOX_IOCXGLIM     _IOWR(MESSAGEBOX_IOC_MAGIC, 14, int)
#define MESSAGEBOX_IOCXULIM     _IOWR(MESSAGEBOX_IOC_MAGIC, 15, int)

#define MESSAGEBOX_IOCHMODE     _IO(MESSAGEBOX_IOC_MAGIC,   16)
#define MESSAGEBOX_IOCHGLIM     _IO(MESSAGEBOX_IOC_MAGIC,   17)
#define MESSAGEBOX_IOCHULIM     _IO(MESSAGEBOX_IOC_MAGIC,   18)

#define MESSAGEBOX_IOC_MAXNR 18

#endif
